#!/usr/bin/env python3
import argparse
import yaml
import json
import pprint
import requests
import getpass
import sys
import jinja2

class JawsRunner:
    def __init__(self, conf):
        self.conf = conf
        self.pp = pprint.PrettyPrinter()
        self.s = requests.Session()
        
        if "vars" in conf.keys() and conf["vars"] is not None:
            self.vars = conf["vars"]
        else:
            self.vars = {}

        if conf["headers"] is not None:
            self.s.headers.update(conf["headers"])

        if "auth" in conf.keys():
            if "username" in conf["auth"].keys() and conf["auth"]["username"] is not None:
                username = self.interpret(conf["auth"]["username"])
            else:
                username = input("Username: ")

            if "password" in conf["auth"].keys() and conf["auth"]["password"] is not None:
                password = self.interpret(conf["auth"]["password"])
            else:
                password = str(getpass.getpass("%s password:" % username))

        self.s.auth = (username, password)

    def run(self):
        for task in self.conf["tasks"]:
            print("### %s ###" % task["name"])
            
            if "data" in task.keys() and task["data"] is not None:
                data = json.dumps(self.interpret(task["data"]))
            else:
                data = None

            if "verbose" in self.conf.keys() and self.conf["verbose"]: print("  - Payload: %s" % data)

            if "stub_override" in task.keys() and task["stub_override"]:
                url = task["stub_override"]
            else:
                url = self.conf["stub"]

            if "verbose" in self.conf.keys() and self.conf["verbose"]: print("  - URL: %s/%s" % (url,task["uri"]))

            if "req" not in task.keys() or task["req"] is None:
                print("No Action specified, bailing out!")
                break
            elif task["req"] == "get":
                t = self.s.get("/".join([url, self.interpret(task["uri"])]), data = data)
            elif task["req"] == "post":
                t = self.s.post("/".join([url, self.interpret(task["uri"])]), data = data)
            elif task["req"] == "delete":
                t = self.s.delete("/".join([url, self.interpret(task["uri"])]), data = data)
            elif task["req"] == "put":
                t = self.s.put("/".join([url, self.interpret(task["uri"])]), data = data)
            
            if str(t.status_code) not in ["404", "403", "402", "401"]:
                print("  - Status: SUCCESS")
            else:
                print("  - Status: ERROR")

            show_types = ["content", "status_code", "headers"]
            if "output" not in task.keys() or "type" not in task["output"].keys() or task["output"]["type"] is None or task["output"]["type"] == "":
                continue

            elif task["output"]["type"] == "print":
                if "show" in task["output"].keys() and task["output"]["show"] in show_types:
                    print(getattr(t, task["output"]["show"]))
                elif task["output"]["show"] == "vars":
                    self.pp.pprint(self.vars)
                elif task["output"]["show"] == "template":
                    if "template_str" in task["output"].keys() and task["output"]["template_str"] is not None:
                        print(self.interpret(task["output"]["template_str"], json.loads(t.content.decode('utf8'))))
                else:
                    print(t.content)
            
            elif task["output"]["type"] == "var":
                if "name" in task["output"].keys() and task["output"]["name"] is not None:
                    vname = task["output"]["name"]
                    if "show" in task["output"].keys() and task["output"]["show"] in show_types:
                        self.vars[vname] = json.loads(getattr(t, task["output"]["show"]))
                else:
                    print("Variables must have names!")
                    sys.exit(-1)

            elif task["output"]["type"] == "store":
                if "name" in task["output"]:
                    fh = task["output"]["name"]
                else:
                    fh = input("Storage file: ")
                if "show" in task["output"].keys() and task["output"]["show"] in show_types:
                    with open(fh, "w+") as f:
                        json.dump(json.loads(task["output"]["show"]), f)
                else:
                    with open(fh, "w+") as f:
                        json.dump(json.loads(t.content), f)

    def interpret(self, string, args=None):
        if not args:
            args = self.vars
        try:
            template = jinja2.Environment(loader=jinja2.BaseLoader).from_string(string)
            output = template.render(**args)
        except TypeError:
            output = string

        return output

    def dump_vars(self):
        template = jinja2.Environment(loader=jinja2.BaseLoader).from_string("{% for issue in issues.issues %}{{ issue.key }}\n{% endfor %}")
        output = template.render(**self.vars)
        print(output)

def main(args):
    conf = yaml.safe_load(open(args.jobfile, "r"))
    j = JawsRunner(conf)
    j.run()
#    j.dump_vars()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="PyF(etch)")
    parser.add_argument("-j", "--jobfile", default=None, help="YAML Jobfile")
    
    args = parser.parse_args()
    main(args)
