#!/usr/bin/env python3
import argparse
import getpass
import jinja2
import json
import pprint
import requests
import sys
import urllib
import yaml

class WarpRunner:
    def __init__(self, conf):
        self.conf = conf
        self.pp = pprint.PrettyPrinter()
        self.s = requests.Session()
        
        self.actions = ["dump", "request"]
        self.show_types = ["content", "status_code", "headers"]
        
        self.verbose = False
        # Set Job verbosity
        if "verbose" in self.conf.keys(): 
            self.verbose = self.conf["verbose"]

        self.urlencode = False
        # set urlencoding as false by default
        if "urlencode" in self.conf.keys() and self.conf["urlencode"]:
            self.urlencode = self.conf["urlencode"]

        # Read in Job vars
        if "vars" in conf.keys() and conf["vars"] is not None:
            self.vars = conf["vars"]
        else:
            self.vars = {}

        # Read in Job Headers
        if "headers" in conf.keys() and conf["headers"] is not None:
            self.headers = conf["headers"]
            self.__set_headers(self.headers)

        # Authenticate if specified
        if "auth" in conf.keys():
            if "username" in conf["auth"].keys() and conf["auth"]["username"] is not None:
                self.username = self.__interpret(conf["auth"]["username"])
            else: self.username = input("Username: ")

            if "password" in conf["auth"].keys() and conf["auth"]["password"] is not None:
                self.password = self.__interpret(conf["auth"]["password"])
            else: self.password = getpass.getpass("%s password: "% self.username)
            self.__auth(self.username, self.password)

        # SSL Friendly certs settings
        if "certs" in conf.keys() and conf["certs"] is not None:
            self.certs = conf["certs"]
            self.__set_certs(self.certs)

    def __interpret(self, string, args=None):
        if not args:
            args = self.vars
        try:
            template = jinja2.Environment(loader=jinja2.BaseLoader).from_string(string)
            output = template.render(**args)
        except TypeError:
            output = string

        return output

    def __auth(self, username=None, password=None):
        if not username: username = input("Username (default: %s): " % self.username)
        if not username: username = self.username
        if not password: password = getpass.getpass("%s password: " % username)
        if not password: password = self.password

        self.s.auth = (username, password)

    def __set_headers(self, headers=None):
        if not headers: headers = self.headers
        self.s.headers.update(headers)

    def __set_certs(self, certs=None):
        if not certs: certs = self.certs
        if "ca_bundle" in conf["certs"].keys() and conf["certs"]["ca_bundle"]:
            self.s.verify = conf["certs"]["ca_bundle"]
        else:
            if self.conf["verbose"]: print("No ca_bundle specified, skipping...")

        certs = []

        if "client" in conf["certs"].keys() and conf["certs"]["client"]:
            certs.append(conf["certs"]["client"])
        else:
            if self.conf["verbose"]: print("No client specified, skipping...")
        
        if "key" in conf["certs"].keys() and conf["certs"]["key"]:
            certs.append(conf["certs"]["key"])
        else:
            if self.conf["verbose"]: print("No key specified, skipping...")

        if len(certs) == 2:
            c = tuple(certs)
            self.s.cert = c
        elif len(certs) == 1:
            print(certs)
            self.s.cert = certs[0]
        
    def __request(self, url, task, data):
        target_url = "/".join([url, self.__interpret(task["uri"])])

        if "urlencode" in task.keys() and task["urlencode"] or self.urlencode:
            target_url = "?".join([target_url, urllib.parse.urlencode(json.loads(data))])
            data = None

        if self.verbose: print("  - URL: %s" % target_url)

        if task["action"]["req"] == "get":
            t = self.s.get(target_url, data = data)
        elif task["action"]["req"] == "post":
            t = self.s.post(target_url, data = data)
        elif task["action"]["req"] == "delete":
            t = self.s.delete(target_url, data = data)
        elif task["action"]["req"] == "put":
            t = self.s.put(target_url, data = data)
        
        if str(t.status_code) not in ["404", "403", "402", "401"]:
            print("  - Status: SUCCESS")
        else:
            print("  - Status: ERROR")

        return(t)

    def __output(self, task, output=None):
        if task["output"]["write_to"] == "var":
            if "name" in task["output"].keys() and task["output"]["name"] is not None:
                vname = task["output"]["name"]
            else:
                print("Variables must have names!")
                sys.exit(-1)
                
            if "content" not in task["output"].keys() or task["output"]["content"] == "raw":
                data = output
            elif task["output"]["content"] in self.show_types:
                data = json.loads(getattr(output, task["output"]["content"]))
            elif task["output"]["content"] == "template":
                if "template_str" in task["output"].keys() and task["output"]["template_str"]:
                    data = self.__interpret(task["output"]["template_str"], json.loads(output.content.decode('utf8')))
                elif "template_file" in task["output"].keys() and task["output"]["template_file"]:
                    data = self.__interpret(open(task["output"]["template_file"], "r").read(), json.loads(output.content.decode('utf8')))
                else: print("No template provided..")

            self.vars[vname] = data

        elif task["output"]["write_to"] == "file":
            # Read in file name
            if "name" in task["output"].keys() and task["output"]["name"] is not None:
                fh = task["output"]["name"]
            else:
                fh = input("Storage file: ")
            f = open(fh, "w+")
           
            if "content" not in task["output"].keys() or task["output"]["content"] == "raw":
                data = output
            elif task["output"]["content"] in self.show_types:
                data = json.dumps(json.loads(getattr(output, task["output"]["content"])))
            elif task["output"]["content"] == "template":
                if "template_str" in task["output"].keys() and task["output"]["template_str"]:
                    data = self.__interpret(task["output"]["template_str"], json.loads(output.content.decode('utf8')))
                elif "template_file" in task["output"].keys() and task["output"]["template_file"]:
                    data = self.__interpret(open(task["output"]["template_file"], "r").read(), json.loads(output.content.decode('utf8')))
                else: print("No template provided..")

            f.write(data) 

        elif task["output"]["write_to"] == "screen":
            if "content" not in task["output"].keys() or task["output"]["content"] == "raw":
                data = output
            elif task["output"]["content"] in self.show_types:
                data = json.dumps(json.loads(getattr(output, task["output"]["content"])))
            elif task["output"]["content"] == "template":
                if "template_str" in task["output"].keys() and task["output"]["template_str"]:
                    data = self.__interpret(task["output"]["template_str"], json.loads(output.content.decode('utf8')))
                elif "template_file" in task["output"].keys() and task["output"]["template_file"]:
                    data = self.__interpret(open(task["output"]["template_file"], "r").read(), json.loads(output.content.decode('utf8')))
                else: print("No template provided..")

            self.pp.pprint(data)

    def run(self):
        # Evaluate potential iteration before the task actually runs
        for task in self.conf["tasks"]:
            print("### %s ###" % task["name"])
            if "loop" in task.keys() and task["loop"] is not None:
                if "items" in task["loop"].keys() and task["loop"]["items"] is not None:
                    taskitems = json.loads(self.__interpret(task["loop"]["items"]).replace("'", "\""))
                else:
                    print("No Items provided... Stopping.")
                    sys.exit(2)
                if "iter_name" in task["loop"].keys() and task["loop"]["iter_name"] is not None:
                    itemname = task["loop"]["iter_name"]
                else:
                    print("No Iterator provided... Stopping.")
                    sys.exit(2)

                for taskitem in taskitems:
                    t_vars = {}
                    t_vars[itemname] = taskitem
                    t = task.copy()
                    t.pop("loop")
                    self.vars = {**self.vars, **t_vars}
                    self.run_task(self.__interpret(t))
            else:
                # No iteration found, JFDI.
                self.run_task(task)

    def run_task(self, task):
            # Read in payload data
            if "data" in task.keys() and task["data"] is not None:
                data = self.__interpret(json.dumps(task["data"]))
            else:
                data = None
            if self.verbose: print("  - Payload: %s" % data)

            # Read in stub_override
            if "stub_override" in task.keys() and task["stub_override"]:
                url = task["stub_override"]
            else:
                url = self.conf["stub"]

            # Evaluate Action Statement
            if "action" not in task.keys() or not isinstance(task["action"], dict):
                print("Invalid Action specified, bailing out!")

            # Request
            if "req" in task["action"].keys():
                t = self.__request(url, task, data)
            
            # Dump
            elif "dump" in task["action"].keys():
                t = self.__interpret(task["action"]["dump"])

            if "output" in task.keys():
                self.__output(task, t) 

def main(args):
    conf = yaml.safe_load(open(args.jobfile, "r"))
    job = WarpRunner(conf)
    job.run()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Warwalrux Awesome Rest Parser")
    parser.add_argument("-j", "--jobfile", default=None, help="YAML Jobfile")
    args = parser.parse_args()
    main(args)
