#!/usr/bin/env python3

import argparse
import getpass
import jinja2
import json
import logging
import os
import pprint
import requests
import sys
import urllib
import yaml

# Log Settings
LOGGING = False
LOGFILE = ""
LOGLEVEL = "DEBUG"
LOGFORMAT = "[ %(filename)s.%(funcName)s (L%(lineno)s) ] %(levelname)s: %(message)s"

if LOGGING:
    logger = logging.getLogger(__name__)
    if LOGFILE:
        logging.basicConfig(filename=LOGFILE,format=LOGFORMAT)
    else:
        logging.basicConfig(format=LOGFORMAT)
    
    logger.setLevel(getattr(logging, LOGLEVEL))


class WarpRunner:
    def __init__(self, conf):
        if LOGGING: logger.debug("Initializing new WARP object.")
        if LOGGING: logger.info("Conducting pre-flight checks")
        self.conf = conf
        self.pp = pprint.PrettyPrinter()
        self.s = requests.Session()
        
        self.actions = ["dump", "request"]
        self.show_types = ["content", "status_code", "headers"]
        
        self.verbose = False
        # Set Job verbosity
        if "verbose" in self.conf.keys():
            if LOGGING: logger.debug("setting job output to: %s" % self.verbose)            
            self.verbose = self.conf["verbose"]
       
        # Read in Job vars
        if "vars" in self.conf.keys() and self.conf["vars"] is not None:
            if LOGGING: logger.debug("Found Job vars.")
            self.vars = conf["vars"]
            if "read_vars" in self.vars.keys():
                self.__readFileIntoVar(self.vars["read_vars"])
        else:
            if LOGGING: logger.debug("Initializing empty job vars object")
            self.vars = {}
            
        self.urlencode = False
        # set urlencoding as false by default
        if "urlencode" in self.conf.keys() and self.conf["urlencode"]:
            self.urlencode = self.__interpret(self.conf["urlencode"])
            if LOGGING: logger.debug("Payload format preference set to \"urlencode\"")
        # N.B. this and everything below it relies on __interpret so put it below the vars...
        else:
            if LOGGING: logger.debug("Payload format preference set to: \"JSON\"")
            
        # Set the Job URL 
        if "stub" in self.conf.keys() and self.conf["stub"] is not None:
            self.url = self.__interpret(self.conf["stub"])
            if LOGGING: logger.debug("Setting Job Default URL stub to: %s" % self.url)

        # Read in Job Headers
        if "headers" in conf.keys() and conf["headers"] is not None:
            if LOGGING: logger.debug("Job default headers found!")
            self.headers = json.loads(self.__interpret(json.dumps(conf["headers"]), self.vars))
            self.__set_headers(self.headers)

        # Authenticate if specified
        if "auth" in conf.keys():
            if "username" in conf["auth"].keys() and conf["auth"]["username"] is not None:
                if LOGGING: logger.info("Job default username found.")
                self.username = self.__interpret(conf["auth"]["username"])
            else: self.username = input("Username: ")

            if "password" in conf["auth"].keys() and conf["auth"]["password"] is not None:
                if LOGGING: logger.info("Job default password found.")
                self.password = self.__interpret(conf["auth"]["password"])
            else:
                if LOGGING: logger.info("Job default password not found, securely prompting...")
                self.password = getpass.getpass("%s password: "% self.username)
            self.__auth(self.username, self.password)

        # SSL Friendly certs settings
        if "certs" in conf.keys() and conf["certs"] is not None:
            if LOGGING: logger.debug("Job default certificate definitions found!")
            self.certs = conf["certs"]
            self.__set_certs(self.certs)

    def __interpret(self, string, args=None):
        if LOGGING: logger.debug("Interpreting %s" % type(string))
        if not args:
            if LOGGING: logger.debug("No vars passed, using job vars")
            args = self.vars
        try:
            if LOGGING: logger.debug("Rendering output from string")
            template = jinja2.Environment(loader=jinja2.BaseLoader).from_string(string)
            output = template.render(**args)
            if LOGGING: logger.debug("Returning rendered string")
        except TypeError:
            if LOGGING: logger.info("Not a valid template... returning original input")
            output = string

        return output

    def __objectify(self, string):
        if LOGGING: logger.debug("Received %s" % type(string))
        try:
            if LOGGING: logger.debug("Trying JSON...")
            data = json.loads(string)
        except:
            if LOGGING: logger.debug("JSON Parsing failed!")
            try:
                if LOGGING: logger.debug("Trying YAML...")
                data = yaml.safe_load(string)
            except:
                if LOGGING: logger.debug("YAML Parsing failed!, Returning %s" % type(string))
                data = string
        return(data)

    def __auth(self, username=None, password=None):
        if not username: 
            if LOGGING: logger.debug("no username passed! prompting")
            username = input("Username (default: %s): " % self.username)
        if not password:
            if LOGGING: logger.debug("No password provided! Securely prompting...")
            password = getpass.getpass("%s password: " % username)
            
        if LOGGING: logger.info("Setting authentication details")
        self.s.auth = (username, password)

    def __set_headers(self, headers=None):
        if not headers:
            if LOGGING: logger.debug("No special headers provided, Using job default headers")
            headers = self.headers
        if LOGGING: logger.info("Setting headers")
        self.s.headers.update(headers)

    def __set_certs(self, certs=None):
        if not certs:
            certs = self.certs
            if LOGGING: logger.info("No special certificates provided, Using job default certificates")
            
        if "ca_bundle" in conf["certs"].keys() and conf["certs"]["ca_bundle"]:
            if LOGGING: logger.info("Found ca bundle certificate")
            self.s.verify = conf["certs"]["ca_bundle"]
        else:
            if self.conf["verbose"]: print("No ca_bundle specified, skipping...")

        certs = []

        if "client" in conf["certs"].keys() and conf["certs"]["client"]:
            if LOGGING: logger.info("Found client certificate")
            certs.append(conf["certs"]["client"])
        else:
            if self.conf["verbose"]: print("No client specified, skipping...")
        
        if "key" in conf["certs"].keys() and conf["certs"]["key"]:
            if LOGGING: logger.info("Found a keyfile")
            certs.append(conf["certs"]["key"])
        else:
            if self.conf["verbose"]: print("No key specified, skipping...")

        if len(certs) == 2:
            c = tuple(certs)
            self.s.cert = c
        elif len(certs) == 1:
            c = certs[0]
        
        if LOGGING: logger.debug("Setting certificates")
        self.s.cert = c
        
    def __request(self, url, task, data):
        if LOGGING: logger.info("Setting target URL")
        target_url = "/".join([url, self.__interpret(task["uri"], self.vars)])

        if "urlencode" in task.keys() and task["urlencode"] or self.urlencode:
            if LOGGING: logger.info("URL encoding preference detected, parsing data into url.")
            target_url = "?".join([target_url, urllib.parse.urlencode(json.loads(data))])
            data = None

        if self.verbose: print("  - URL: %s" % target_url)

        if task["action"]["req"] == "get":
            if LOGGING: logger.info("Running GET request")
            t = self.s.get(target_url, data = data)
        elif task["action"]["req"] == "post":
            if LOGGING: logger.info("Running POST request")
            t = self.s.post(target_url, data = data)
        elif task["action"]["req"] == "delete":
            if LOGGING: logger.info("Running DELETE request")
            t = self.s.delete(target_url, data = data)
        elif task["action"]["req"] == "put":
            if LOGGING: logger.info("Running PUT request")
            t = self.s.put(target_url, data = data)
        
        if str(t.status_code) in ["200"]:
            if self.verbose: print("  - Status: SUCCESS")
        else:
            if LOGGING: logger.critical("Request Status Code: %s" % t.status_code, exc_info=True)
            if self.verbose: print("  - Status: ERROR")

        return(t)

    def __readFileIntoVar(self, var_file):
        if LOGGING: logger.info("Reading vars file into job vars")
        if "to_name" in var_file.keys() and var_file["to_name"] is not None:
            varname = self.__interpret(var_file["to_name"])
        else:
            if LOGGING: logger.critical("Variables must have names", exc_info=True)
            print("vars must have names")
            sys.exit(-1)

        if "var_file" in var_file.keys() and os.path.isfile(var_file["var_file"]):
            if LOGGING: logger.info("%s exists" % var_file["var_file"])
            if self.verbose:
                if LOGGING: logger.debug("Reading %s" % var_file["var_file"])
                print("  - Reading vars from: %s" % var_file["var_file"])
            data = yaml.safe_load(open(var_file["var_file"], "r").read())
        else:
            if LOGGING: logger.error("%s doesn't exist :(" % var_file["var_file"])
            print("not a valid file...")
            sys.exit(-1)
    
        self.vars[varname] = data
 
    def __output(self, task, output=None):
        if LOGGING: logger.debug("Received %s, objectifying..." % type(output))
        
        # Objectify all the things (try to interpret it as a dict otherwise return the string we sent)
        output = self.__objectify(output)
        
        # Wrangle content settings and mangle the output to fit.
        if "content" not in task["output"].keys() or task["output"]["content"] == "raw":
            if LOGGING: logger.info("Setting output data to the raw object")
            data = output
        elif task["output"]["content"] in self.show_types:
            if "req" in task["action"]:
                if LOGGING: logger.info("Setting output data to requests.%s" % task["output"]["content"])
                data = self.__objectify((getattr(output, task["output"]["content"])))
            else:
                if LOGGING: logger.error("Invalid use of 'content' keyword")
                print("content: %s can only be used with request actions"%(task["output"]["content"]))
        elif task["output"]["content"] == "template":
            if LOGGING: logger.info("Setting output data to templated string")
            if "template_str" in task["output"].keys() and task["output"]["template_str"]:
                if "req" in task["action"]:
                    data = self.__interpret(task["output"]["template_str"], output.content.decode('utf8'))
                elif isinstance(output, dict):
                    data = self.__interpret(task["output"]["template_str"], output)
                else:
                    print("vars object must be used for templating...")
            elif "template_file" in task["output"].keys() and task["output"]["template_file"]:
                if "req" in task["action"]:
                    data = self.__interpret(open(task["output"]["template_file"], "r").read(), output.content.decode('utf8'))
                elif isinstance(output, dict):
                    data = self.__interpret(open(task["output"]["template_file"], "r").read(), output)
                else:
                    print("vars object must be used for templating...")
            else:
                if LOGGING: logger.error("No template provided.") 
                print("No template provided..")

        # Do the output redirection to the users preferred destination
        if task["output"]["write_to"] == "var":
            if "name" in task["output"].keys() and task["output"]["name"] is not None:
                vname = task["output"]["name"]
            else:
                if LOGGING: logger.critical("Variables must have names!")
                print("Variables must have names!")
                sys.exit(-1)
                
            if LOGGING: logger.info("Setting var: %s" % vname)
            self.vars[vname] = data

        elif task["output"]["write_to"] == "file":
            # Read in file name
            if "name" in task["output"].keys() and task["output"]["name"] is not None:
                fh = task["output"]["name"]
                if LOGGING: logger.info("Setting filehandle to: %s" % fh)
            else:
                if LOGGING: logger.info("No filehandle specified, prompting for filename...")
                fh = input("Storage file: ")
            if LOGGING: logger.debug("Opening %s for writing" % fh)
            f = open(fh, "w+")
            
            if LOGGING: logger.debug("Writing json dump to file.")
            f.write(json.dumps(data))

        elif task["output"]["write_to"] == "screen":
            if LOGGING: logger.debug("Pretty printing to screen")
            self.pp.pprint(data)

    def __run_task(self, task):
            # Read in payload data
            if "data" in task.keys() and task["data"] is not None:
                data = self.__interpret(json.dumps(task["data"]))
                if LOGGING: logger.debug("Found payload data!")
            else:
                if LOGGING: logger.debug("Payload Data set to None")
                data = None
            if self.verbose: print("  - Payload: %s" % data)

            # Read in stub_override
            if "stub_override" in task.keys() and task["stub_override"]:
                if LOGGING: logger.info("task stub override found!")
                url = self.__interpret(task["stub_override"])
            else:
                if LOGGING: logger.info("using default URL")
                url = self.url

            # Evaluate Action Statement
            if "action" not in task.keys() or not isinstance(task["action"], dict):
                if LOGGING: logger.critical("No action specified...")
                print("Invalid Action specified, bailing out!")
                sys.exit(3)
                
            # Request
            if "req" in task["action"].keys():
                if LOGGING: logger.info("Request task detected.")
                t = self.__request(url, task, data)
            
            # Dump
            elif "dump" in task["action"].keys():
                if LOGGING: logger.info("Dump task detected.")
                t = self.__interpret(task["action"]["dump"])

            # Read vars from vars file
            elif "read_vars" in task["action"].keys() and task["action"]["read_vars"] is not None:
                if LOGGING: logger.info("Read var_file task detected.")
                self.__readFileIntoVar(task["action"]["read_vars"])

            if "output" in task.keys():
                if LOGGING: logger.info("Task output directive detected,")
                self.__output(task, t)
                
    def run(self):
        # Evaluate potential iteration before the task actually runs
        if LOGGING: logger.info("beginning job tasks...")
        for task in self.conf["tasks"]:
            if self.verbose: print("### %s ###" % task["name"])
            else: print("running: %s" % task["name"])
            if "loop" in task.keys() and task["loop"] is not None:
                if LOGGING: logger.info("Task iteration detected")
                if "items" in task["loop"].keys() and task["loop"]["items"] is not None:
                    taskitems = json.loads(self.__interpret(task["loop"]["items"]).replace("'", "\""))
                    if LOGGING: logger.debug("task items received.")
                else:
                    if LOGGING: logger.critical("No task items received!")
                    print("No loop items provided... Stopping.")
                    sys.exit(2)
                if "iter_name" in task["loop"].keys() and task["loop"]["iter_name"] is not None:
                    if LOGGING: logger.debug("task iterator name received.")
                    itemname = task["loop"]["iter_name"]
                else:
                    if LOGGING: logger.critical("No task iterator name set!")
                    print("No Iterator provided... Stopping.")
                    sys.exit(2)

                if LOGGING: logger.info("Iterating through items")
                for taskitem in taskitems:
                    if LOGGING: logger.debug("Creating temporary vars")
                    t_vars = {}
                    if LOGGING: logger.debug("setting current item to: %s"%itemname)
                    t_vars[itemname] = taskitem
                    if LOGGING: logger.debug("Creating a loopless copy of the current task")
                    t = task.copy()
                    t.pop("loop")
                    if LOGGING: logger.debug("Merging temporary_vars into job vars")
                    self.vars = {**self.vars, **t_vars}
                    if LOGGING: logger.debug("Running the currently iterated copy of the task")
                    self.__run_task(self.__interpret(t))
            else:
                # No iteration found, JFDI.
                if LOGGING: logger.debug("No iteration detected, running .")
                self.__run_task(task)


def main(args):
    conf = yaml.safe_load(open(args.jobfile, "r"))
    job = WarpRunner(conf)
    job.run()

if __name__ == "__main__":   
    parser = argparse.ArgumentParser(description="Warwalrux Awesome Rest Parser")
    parser.add_argument("-j", "--jobfile", required=True, default=None, help="YAML Jobfile")
    args = parser.parse_args()
    main(args)
